root: ./docs/

structure:
    readme: Home.md
    summary: summary.md

redirects:  
    architecture/architecture: Mosip-Architecture.md
    biometric-data-specification: Biometric-Specification.md
    