root: ./docs/

structure:
    readme: Home.md
    summary: summary.md

redirects:  
    architecture/architecture: Mosip-Architecture.md
    biometrics/biometric-data-specification: biometrics/biometric-specification
    