openapi: 3.0.1,
info:
  title: Secure Biometric Interface
  description: "[Overview](https://docs.mosip.io/1.2.0/biometrics/secure-biometric-interface)."
  license:
    name: Mozilla Public License Version 2.0
    url: https://www.mozilla.org/en-US/MPL/2.0/
  version: 0.9.5

paths:
  /device:
    post: 
      summary: Device discovery
      description: Device discovery is used to identify MOSIP compliant devices in a system.  
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: ['type']
              properties:
                type:
                  description: Type of device.
                  type: string 
                  enum:
                    - Finger
                    - Face
                    - Iris
                    - Biometric Device
      responses:
        '200':
          description: Array of discovered devices.
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/deviceDiscoveryInfo'  
  /info:
    post: 
      summary: Device info
      description: The request is used to identify the MOSIP compliant devices and their status by the applications.
      responses:
        '200':
          description: "Array of devices running on a particular port of [SBI Service](https://docs.mosip.io/1.2.0/biometrics/secure-biometric-interface) instance"
          content: 
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required: ['deviceInfo', 'error']
                  properties:
                    deviceInfo:                       
                      type: string
                      format: byte
                      description: "* `base64urlencode(header).base64urlencode(deviceInfo).base64urlencode(signature)` for registered device.\n* `base64urlencode(deviceInfo)` for unregistered device.\n\nSee `deviceInfo` JSON structure."
                    error: 
                      $ref: '#/components/schemas/error'     
                      
  /capture:
    post: 
      summary: Capture
      description: This request is used to capture a biometric from MOSIP compliant devices.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: ['type']
              properties:
                env:
                  $ref: '#/components/schemas/environment'
                purpose:
                  $ref: '#/components/schemas/purpose'
                specVersion:
                  $ref: '#/components/schemas/specVersion'
                timeout:
                  $ref: '#/components/schemas/timeout'
                domainUri:
                  description: URI of the auth server.
                  type: string
                transactionId:
                  description: Transaction Id for the current capture.
                  type: string
                bio:
                  description:
                  type: array
                  items:
                    $ref: '#/components/schemas/bio'  
                customOpts:
                  type: object 
                  description: "Vendor specific parameters. Max of 50 key value pairs. IMPORTANT: Any sensitive data should not be present here."
      responses:
        '200':
          description: Array of biometrics
          content: 
            application/json:
              schema:
                type: object
                properties:
                  biometrics:
                    type: array
                    items:
                      $ref: '#/components/schemas/captureBiometrics'  

  /stream:
    post: 
      summary: Video stream
      description: "The device starts a live video stream of biometric images. This API shall be exposd only by devices with purpose as **Registration**."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: ['deviceId', 'deviceSubId']
              properties:
                deviceId:
                  $ref: '#/components/schemas/deviceId'  
                deviceSubId:
                  type: integer
                  description: "[Device SubId](https://docs.mosip.io/1.2.0/biometrics/secure-biometric-interface#device-subid)."
                timeout: 
                  $ref: '#/components/schemas/timeout'  
      responses:
        '200':
          description: "[MJPEG](https://en.wikipedia.org/wiki/Motion_JPEG) video stream with minimum 3 fps or error" 
          content: 
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: '#/components/schemas/error'
  /non-existent-endpoint:
    post:
      description: "Documentation of `deviceInfo` JSON structure."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                deviceInfo:
                  $ref: '#/components/schemas/deviceInfo'

components:
  schemas:
    specVersion:
      type: array
      description: Supported SBI versions.
      items:
        type: string
    deviceCode:
      type: string
      description: Code generated by the Device Provider.
    certification:
      type: string
      description: Certification level.
      enum: 
        - L0
        - L1
    timeout:
      type: integer
      description: Timeout in milliseconds
      default: 300000 
    deviceId:
      type: string
      description: Internal ID of the device
    environment:
      type: string
      description: Target environment.
      enum:
        - Staging 
        - Developer
        - Pre-Production
        - Production
    purpose:
      description: 
      type: string
      enum:
        - Auth
        - Registration 
    deviceStatus:
       type: string
       description: 
       enum:
         - Ready
         - Busy
         - Not Ready
         - Not Registered
    captureBiometrics:
      type: object
      description:
      properties:
        specVersion: 
          $ref: '#/components/schemas/specVersion'  
        data:
          $ref: '#/components/schemas/bioData'  
        hash:
          type: string
          description: sha256(sha256 hash in hex format of the previous data block + sha256 hash in hex format of the current data block before encryption)
        sessionKey:
          type: string
          description: Encrypted with MOSIP public key (dynamically selected based on the uri) and encoded session key biometric"
        thumbprint:
          type: string
          description: SHA256 representation of thumbprint of the certificate that was used for encryption of session key. All texts to be treated as uppercase without any spaces or hyphens
        error:
          $ref: '#/components/schemas/error'     

    bioData:
      type: object
      properties:
        digitalId:
          type: string
          description: "[Reference](https://docs.mosip.io/1.2.0/biometrics/secure-biometric-interface#digital-id)."
        deviceCode: 
          $ref: '#/components/schemas/deviceCode'
        deviceServiceVersion: 
          type: string
          description: SBI version
        bioType: 
          type: string
          description: 
          enum:
            - Finger
            - Iris
            - Face
        bioSubType: 
          type: string
          description: "[Subtypes](https://docs.mosip.io/1.2.0/biometrics/secure-biometric-interface#biometric-subtype)."
        purpose: 
          $ref: '#/components/schemas/purpose'
        env: 
          $ref: '#/components/schemas/environment'
        domainUri:
          type: string
          description: URI of the auth server.
        bioValue: 
          type: string
          description: Encrypted with session key and base64urlencoded biometric data.
        transactionId: 
          type: string
          description: Unique transaction id.
        timestamp: 
          type: string
          description: Capture datetime in ISO format.
        requestedScore: 
          type: number
          description: Floating point number to represent the minimum required score for the capture.
        qualityScore: 
          type: number
          description: Floating point number representing the score for the current capture.
    bio:
      type: object
      properties:
        type: 
          description: Type of the biometric data.
          type: string
        count:
          description: Finger/iris count. 1 in case of face.
          type: integer
        bioSubType:
          description: "[Subtypes](https://docs.mosip.io/1.2.0/biometrics/secure-biometric-interface#biometric-subtype)."
          type: array
          items:
            type: string
        requestedScore:
          description: 
          type: string
        deviceId:  
          $ref: '#/components/schemas/deviceId'  
        deviceSubId:
          type: integer
          description: "[Device SubId](https://docs.mosip.io/1.2.0/biometrics/secure-biometric-interface#device-subid)."
        previousHash:
          type: string
          description: Hash of the previous block.
          
    deviceDiscoveryInfo:
      type: object
      properties:
        deviceId:  
          $ref: '#/components/schemas/deviceId'  
        deviceStatus:  
          $ref: '#/components/schemas/deviceStatus'  
        certification:
          $ref: '#/components/schemas/certification'  
        serviceVersion:
          type: string
          description: Device service version.
        deviceSubId:
          type: array
          description: "[Device SubId](https://docs.mosip.io/1.2.0/biometrics/secure-biometric-interface#device-subid)."
          items:
            type: integer
        callbackId:
          type: string
          description: "Base URL to reach device.\n* Linux and windows: HTTP URL\n* Android: Intent name\n* IOS: URL schema."
        digitalId:
          type: string
          description: "[Unsigned digital ID](https://docs.mosip.io/1.2.0/biometrics/secure-biometric-interface#device-digital-id)."
        deviceCode:
          $ref: '#/components/schemas/deviceCode'
        specVersion:
          $ref: '#/components/schemas/specVersion'
        purpose:
          $ref: '#/components/schemas/purpose'
        error:
          type: object 
          properties:
            errorCode:
              type: string
              description: "[Error codes](https://docs.mosip.io/1.2.0/biometrics/secure-biometric-interface#error-codes)."
            errorInfo: 
              type: string
              description: ""
    deviceInfo:
      type: object
      properties:
        deviceId:  
          $ref: '#/components/schemas/deviceId'  
        deviceStatus:  
          $ref: '#/components/schemas/deviceStatus'  
        firmware:
          type: string
          description: Firmware version 
        certification:
          $ref: '#/components/schemas/certification'  
        serviceVersion:
          type: string
          description: Device service version.
        deviceSubId:
          type: array
          description: "[Device SubId](https://docs.mosip.io/1.2.0/biometrics/secure-biometric-interface#device-subid)."
          items:
            type: integer
        callbackId:
          type: string
          description: "Base URL to reach device.\n* Linux and windows: HTTP URL\n* Android: Intent name\n* IOS: URL schema."
        digitalId:
          type: string
          description: "[Signed digital ID](https://docs.mosip.io/1.2.0/biometrics/secure-biometric-interface#device-digital-id)."
        deviceCode:
          $ref: '#/components/schemas/deviceCode'
        env: 
          $ref: '#/components/schemas/environment'
        specVersion:
          $ref: '#/components/schemas/specVersion'
        purpose:
          $ref: '#/components/schemas/purpose'
        error:
          type: object 
          properties:
            errorCode:
              type: string
              description: "[Error codes](https://docs.mosip.io/1.2.0/biometrics/secure-biometric-interface#error-codes)."
            errorInfo: 
              type: string
              description: ""
    error:
      type: object 
      properties:
        errorCode:
          type: string
          description: "[Error codes](https://docs.mosip.io/1.2.0/biometrics/secure-biometric-interface#error-codes)."
        errorInfo: 
          type: string
          description: ""
