openapi: 3.0.1,
info:
  title: Secure Biometric Interface
  description: "[Overview]()."
  license:
    name: Mozilla Public License Version 2.0]
    url: https://www.mozilla.org/en-US/MPL/2.0/
  version: 0.9.5

paths:
  /device:
    post: 
      summary: Device discovery
      description: Device discovery is used to identify MOSIP compliant devices in a system.  
      required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: ['type']
              properties:
                type:
                  description: Type of device.
                  type: string 
                  enum:
                    - Finger
                    - Face
                    - Iris
                    - Biometric Device
      responses:
        '200':
          description: Array of discovered devices.
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/deviceInfo'  
  /capture:
    post: 
      summary: Capture
      description: This request is used to capture a biometric from MOSIP compliant devices.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: ['type']
              properties:
                env:
                  description: Target environment.
                  type: string
                purpose:
                  $ref: '#/components/schemas/purpose'
                specVersion:
                  description: Expected version of the SBI spec.
                  type: string
                timeout:
                  description: Timeout for capture.
                  type: string
                domainUri:
                  description: URI of the auth server.
                  type: string
                transactionId:
                  description: Transaction Id for the current capture.
                  type: string
                bio:
                  description:
                  type: array
                  items:
                    $ref: '#/components/schemas/bio'  
                customOpts:
                  type: object 
                  description: "Vendor specific parameters. Max of 50 key value pairs. IMPORTANT: Any sensitive data should not be present here."
      responses:
        '200':
          description: Array of biometrics
          content: 
            application/json:
              schema:
                type: object
                properties:
                  biometrics:
                    type: array
                    items:
                      $ref: '#/components/schemas/captureBiometrics'  

components:
  schemas:
    purpose:
      description: 
      type: string
      enum:
        - Auth
        - Registration 
    deviceStatus:
       type: string
       description: 
       enum:
         - Ready
         - Busy
         - Not Ready
         - Not Registered
    captureBiometrics:
      type: object
      description:
      properties:
        specVersion: 
          type: string
          description: SBI version
        data:
          $ref: '#/components/schemas/bioData'  
        hash:
          type: string
          description: sha256(sha256 hash in hex format of the previous data block + sha256 hash in hex format of the current data block before encryption)
        sessionKey:
          type: string
          description: Encrypted with MOSIP public key (dynamically selected based on the uri) and encoded session key biometric"
        thumbprint:
          type: string
          description: SHA256 representation of thumbprint of the certificate that was used for encryption of session key. All texts to be treated as uppercase without any spaces or hyphens
        error:
          $ref: '#/components/schemas/error'     

    bioData:
      type: object
      properties:
        digitalId:
          type: string
          description: "[Reference](https://docs.mosip.io/1.2.0/biometrics/secure-biometric-interface#digital-id)."
        deviceCode: 
          type: string
          description: "_Unused_."
        deviceServiceVersion: 
          type: string
          description: SBI version
        bioType: 
          type: string
          description: 
          enum:
            - Finger
            - Iris
            - Face
        bioSubType: 
          type: string
          description: "[Subtypes](https://docs.mosip.io/1.2.0/biometrics/secure-biometric-interface#biometric-subtype)."
        purpose: 
          $ref: '#/components/schemas/purpose'
        env: 
          type: string
          description: Target environment.
        domainUri:
          type: string
          description: URI of the auth server.
        bioValue: 
          type: string
          description: Encrypted with session key and base64urlencoded biometric data.
        transactionId: 
          type: string
          description: Unique transaction id.
        timestamp: 
          type: string
          description: Capture datetime in ISO format.
        requestedScore: 
          type: number
          description: Floating point number to represent the minimum required score for the capture.
        qualityScore: 
          type: number
          description: Floating point number representing the score for the current capture.
    bio:
      type: object
      properties:
        type: 
          description: Type of the biometric data.
          type: string
        count:
          description: Finger/iris count. 1 in case of face.
          type: integer
        bioSubType:
          description: "[Subtypes](https://docs.mosip.io/1.2.0/biometrics/secure-biometric-interface#biometric-subtype)."
          type: array
          items:
            type: string
        requestedScore:
          description: 
          type: string
        deviceId:  
          type: string
          description: Internal id of the device.
        deviceSubId:
          type: integer
          description: "[Device SubId](https://docs.mosip.io/1.2.0/biometrics/secure-biometric-interface#device-subid)."
        previousHash:
          type: string
          description: Hash of the previous block.
          
    deviceInfo:
      type: object
      properties:
        deviceId:  
          type: string
          description: Internal id of the device.
        deviceStatus:  
          $ref: '#/components/schemas/deviceStatus'  
        certification:
          type: string
          description: Certification level.
          enum: 
            - L0
            - L1
        serviceVersion:
          type: string
          description: Device service version.
        deviceSubId:
          type: array
          description: "[Device SubId](https://docs.mosip.io/1.2.0/biometrics/secure-biometric-interface#device-subid)."
          items:
            type: integer
        callbackId:
          type: string
          description: "Base URL to reach device.\n* Linux and windows: HTTP URL\n* Android: Intent name\n* IOS: URL schema."
        digitalId:
          type: string
          description: "[Reference](https://docs.mosip.io/1.2.0/biometrics/secure-biometric-interface#digital-id)."
        deviceCode:
          type: string
          description: A unique code given by MOSIP after successful registration.
        specVersion:
          type: array
          description: Supported SBI versions.
          items:
            type: string
        purpose:
          $ref: '#/components/schemas/purpose'
        error:
          type: object 
          properties:
            errorCode:
              type: string
              description: "[Error codes](https://docs.mosip.io/1.2.0/biometrics/secure-biometric-interface#error-codes)."
            errorInfo: 
              type: string
              description: ""
    error:
      type: object 
      properties:
        errorCode:
          type: string
          description: "[Error codes](https://docs.mosip.io/1.2.0/biometrics/secure-biometric-interface#error-codes)."
        errorInfo: 
          type: string
          description: ""



