name: Publish Document for a Release

# Triggered when code is pushed to any branch in a repository
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Trigger HTML Documentation'
        required: false
        default: 'Document Preparation'
      git-ref:
        description: 'tag to generate document'
        required: true

jobs:
  Generate_Documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Checkout Repository
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}

      - name: Setup Branch and Env
        run: |
          # Strip git ref prefix from version
          echo "BRANCH_NAME=${{ github.event.inputs.git-ref }}" >> $GITHUB_ENV

      - name: Set up redoc cli
        run: |
          npm install -g redoc-cli

      - name: Generate HTML Document with JSON
        run: |
          mkdir -p html_docs
          find ./api -name "*openapi.json" -exec readlink -f {} \; > tmp.txt
          while IFS= read -r line
          do
            fullpath=$line
            echo "Pullpath: $fullpath"
            fullname=$(basename "$line")
            echo "Filename: $fullname"
            filename=$(echo "$fullname" | cut -f 1 -d '.')
            fname=$(filename%-openapi*)
            redoc-cli bundle -o ./html_docs/$filename.html $fullpath
            sed '/\<body\>/a <div class="sc-iCoGMd gLxhOh">   <div class="sc-hKFxyN juinod"><h4><a href="${{ github.event.inputs.git-ref }}.html">Home</a>   </h4></div></div>' ./html_docs/$filename.html > ./html_docs/$fname.html
            rm -fr ./html_docs/$filename.html
          done < tmp.txt

      - name: Upload HTML Documents as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: html_docs
          path: ./html_docs/*.html
          retention-days: 1

      - name: Checkout branch for publishing
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Download HTML Documents from Artifacts
        uses: actions/download-artifact@v2
        with:
          name: html_docs
          path: ./${{ github.event.inputs.git-ref }}/

      - name: Check All Files
        run: |
          echo "$(find ./{{ github.event.inputs.git-ref }} -name "*openapi.html" -exec readlink -f {} \;)"

      - name: Create link html file
        run: |
          chmod +x index-creator.sh
          bash index-creator.sh ${{ github.event.inputs.git-ref }} > ./${{ github.event.inputs.git-ref }}/${{ github.event.inputs.git-ref }}.html

      - name: Update index html file
        run: |
          echo "<!DOCTYPE html>\n<html>\n<style>\n.content {\n\tmax-width: 700px;\n\tmargin: auto;\n\ttext-align: center;\n}\n</style>\n<body>\n\t<div class='content'>\n\t\t<img src='https://mosip.github.io/mosip-helm/mosip_logo.png'>\n\t\t<h2 style='font-family:verdana;'>MOSIP API Documentation</h2>\n\t\t<a href='${{ github.event.inputs.git-ref }}/${{ github.event.inputs.git-ref }}.html' style='font-family:verdana;'>MOSIP ${{ github.event.inputs.git-ref }}</a>\n\t</div>\n</body>\n</html>" > index.html

      - name: Commit Changes to Documenation Repository
        uses: EndBug/add-and-commit@v7
        with:
          branch: gh-pages
          default_author: github_actions
          message: 'added documentation for release ${{ github.event.inputs.git-ref }}'
          add: './${{ github.event.inputs.git-ref }}/*.html'
